[[main]]
name = "Home"
pre = "is-uppercase"
url = "/"
weight = 1

[[main]]
name = "About"
pre = "is-uppercase"
url = "/about/"
weight = 2

[[main]]
name = "Republication"
pre = "is-uppercase"
url = "/republication/"
weight = 3

[[main]]
name = "Graying Pains"
pre = "is-uppercase"
url = "/graying-pains/"
weight = 4

# [[main]]
# name = "Project 2 TK"
# pre = "is-uppercase"
# url = "/project-2/"
# weight = 5

# Footer col 1

[[footer]]
name = "Home"
pre = "is-uppercase"
url = "/"
weight = 1

[[footer]]
name = "About"
pre = "is-uppercase"
url = "/about/"
weight = 2

[[footer]]
name = "Republication"
pre = "is-uppercase"
url = "/republication/"
weight = 3

# Footer col 2

[[projects]]
name = "Graying Pains"
pre = "is-uppercase"
url = "/graying-pains/"
weight = 1

# [[projects]]
# name = "Project 2 TK"
# pre = "is-uppercase"
# url = "/project-2/"
# weight = 2


# Footer col 3 - turned off

# [[social]]
# name = "Get updates"
# pre = "is-uppercase"
# url = "TK"
# weight = 1

# [[social]]
# name = "Facebook"
# pre = "is-uppercase"
# url = "https://www.facebook.com/SpotlightPennsylvania"
# weight = 1

# [[social]]
# name = "Twitter"
# pre = "is-uppercase"
# url = "https://www.twitter.com/SpotlightPA"
# weight = 2

# [[social]]
# name = "Google News"
# pre = "is-uppercase"
# url = "https://news.google.com/publications/CAAqBwgKMJOpkgswx-CnAw"
# weight = 3

# [[social]]
# name = "Github"
# pre = "is-uppercase"
# url = "https://www.github.com/spotlightpa/"
# weight = 4
