baseURL = "https://www.montanafourthestate.org/"
languageCode = "en-us"
title = "Montana Fourth Estate Project"
enableRobotsTXT = true
enableGitInfo = true
rssLimit = 50

timeout = "240s"

# DONE changed this to MTFP code
googleAnalytics = "UA-70813941-4"

[markup]
defaultMarkdownHandler = "blackfriday"

[privacy.googleAnalytics]
    anonymizeIP = true
    disable = false
    respectDoNotTrack = true
    useSessionStorage = true

[taxonomies]
  author = "authors"

[frontmatter]
    date  = [":default", ":filename"]
    publishDate  = [":default", ":filename"]

[permalinks]
    press-releases = ":section/:year/:slug/"
    news = ":section/:year/:month/:slug/"
    test = ":section/:slug/"

[mediaTypes."text/netlify"]
    delimiter = ""

[outputFormats.jsonfeed]
    mediaType = "application/json"
    baseName = "feed"
    isPlainText = true

[outputFormats.jsonfeedsummary]
    mediaType = "application/json"
    baseName = "feed-summary"
    isPlainText = true

[outputFormats.redirects]
mediatype = "text/netlify"
baseName = "_redirects"
isPlainText = true
notAlternative = true

[outputs]
    home = ["html", "jsonfeed", "rss", "redirects"]
    section = ["html", "jsonfeed", "jsonfeedsummary", "rss"]

[params]
    imgproxy = "/imgproxy/"
    title = ""
    favicon = "/img/logos/mt4-dark-on-trans.png"
    touch-icon = "/img/logos/mt4-dark-on-white.png"
    images = [
        "/img/logos/montana-fourth-estate.png"
    ]
    description = "Description TK"
    extra-footer = ""

[[module.mounts]]
source = "assets"
target = "assets"

[[module.mounts]]
source = "dist"
target = "assets/js"

[[module.mounts]]
source = "dist"
target = "static/js"

[[module.mounts]]
source = "static"
target = "static"

[[related.indices]]
  name = "title"
  weight = 150

[[related.indices]]
  name  = "date"
  weight = 10
  pattern = "2006"
