baseURL = "https://www.spotlightpa.org/"
languageCode = "en-us"
title = "Spotlight PA"
enableRobotsTXT = true
enableGitInfo = true
rssLimit = 50

# TODO: Change this to MTFP code
googleAnalytics = "UA-141126362-1"

[markup]
defaultMarkdownHandler = "blackfriday"

[privacy.googleAnalytics]
    anonymizeIP = true
    disable = false
    respectDoNotTrack = true
    useSessionStorage = true

[taxonomies]
  author = "authors"

[frontmatter]
    date  = [":default", ":filename"]
    publishDate  = [":default", ":filename"]

[permalinks]
    press-releases = ":section/:year/:slug/"
    news = ":section/:year/:month/:slug/"
    test = ":section/:slug/"

[mediaTypes."text/netlify"]
    delimiter = ""

[outputFormats.jsonfeed]
    mediaType = "application/json"
    baseName = "feed"
    isPlainText = true

[outputFormats.jsonfeedsummary]
    mediaType = "application/json"
    baseName = "feed-summary"
    isPlainText = true

[outputFormats.redirects]
mediatype = "text/netlify"
baseName = "_redirects"
isPlainText = true
notAlternative = true

[outputs]
    home = ["html", "jsonfeed", "rss", "redirects"]
    section = ["html", "jsonfeed", "jsonfeedsummary", "rss"]

[params]
    imgproxy = "/imgproxy/"
    title = "Spotlight PA"
    favicon = "/img/logos/circle-black-on-trans-920.png"
    touch-icon = "/img/logos/square-white-on-black-920.png"
    images = [
        "2019/11/banner-white-on-capitol.jpeg"
    ]
    description = "The mission of Spotlight PA is to hold powerful private and public forces across Pennsylvania — especially government, business and special interests — to account through urgent and compelling investigative journalism that leads to change and the betterment of democracy, the state and all who live here."
    extra-footer = 'TK extra footer [language](https://montanafreepress.org)'

[[module.mounts]]
source = "assets"
target = "assets"

[[module.mounts]]
source = "dist"
target = "assets/js"

[[module.mounts]]
source = "dist"
target = "static/js"

[[module.mounts]]
source = "static"
target = "static"

[[related.indices]]
  name = "title"
  weight = 150

[[related.indices]]
  name  = "kicker"
  weight = 100

[[related.indices]]
  name  = "authors"
  weight = 100

[[related.indices]]
  name  = "date"
  weight = 10
  pattern = "2006"
