backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

media_folder: assets/img/uploads
public_folder: /img/uploads

site_url: https://montanafourthestate.org
display_url: https://montanafourthestate.org

editor:
  preview: false
show_preview_links: false

yaml-definitions: &post-fields
  - name: type
    widget: hidden
    default: "story"
  - label: Title
    name: title
    hint: "Title as it appears at top of page"
    widget: string
  - label: Subhed
    name: subtitle
    widget: string
    required: false
    hint: "Appears below title at top of page if set"
  - label: Summary
    name: description
    hint: "Shown in social share previews, search results & website story summaries"
    widget: string
  - label: Date
    name: published
    widget: datetime
    hint: "Note that future dated articles will not be published on the live site"
  - label: Republication Date
    name: republished
    widget: datetime
    hint: "If set, will display in republication box at bottom of story. Defaults to today."
    required: false
  - label: Featured
    name: featured
    widget: boolean
    default: true
    hint: Set as project featured story. Most recent story set as featured displays. Others should filter into story list.
  - label: Pinned
    name: pinned
    widget: boolean
    hint: Stories pinned next to featured story on project page. Most recent pinned stories, up to 2, display. Others should filter into story list.
    default: false
  - label: "Featured Image"
    name: "image"
    widget: image
    required: false
    media_library:
      config:
        multiple: false
  - label: Featured image description
    name: image-description
    widget: string
  - label: Featured image credit
    name: image-credit
    widget: string
    required: false
  - label: "Featured image display"
    name: "image-size"
    widget: "select"
    options: ["inline", "hidden"]
    default: inline
  - label: Byline
    name: byline
    widget: string
    hint: "e.g. Jane Doe, Montana Free Press"
  - label: Additional Credits
    name: additional-credits
    widget: string
    required: false
    hint: "Displayed as text in italics at bottom of story"
  - label: Body
    name: body
    widget: markdown
    hint: Add inline images/graphics/audio with {{<shortcodes src="src-url">}} in markdown view.

collections:
  - label: Graying Pains stories
    label_singular: Graying Pains story
    description: Stories in Graying Pains project
    name: graying-pains
    folder: content/graying-pains
    filter: { field: "type", value: "story" }
    fields: *post-fields
    slug: "gp-{{slug}}"
    format: toml-frontmatter
    extension: md
    create: true
