backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

media_folder: assets/img/uploads
public_folder: /img/uploads

site_url: https://montanafourthestate.org
display_url: https://montanafourthestate.org

show_preview_links: true

yaml-definitions: &post-fields
  - name: type
    widget: "select"
    options: ["story"]
  - label: Hed
    name: title
    hint: "Title as it appears at top of page"
    widget: string
  - label: Subhed
    name: subtitle
    widget: string
    hint: "Appears below hed at top of page; AKA dek"
    required: false
  - label: Summary
    name: description
    hint: "Shown in social share previews, search results + on project page"
    widget: string
  - label: Date
    name: published
    widget: datetime
    hint: "Note that future dated articles will not be published on the live site"
  - label: Pinned
    name: pinned
    widget: boolean
    hint: Stories pinned next to featured story
  - label: "Featured Image"
    name: "image"
    widget: image
    required: false
    media_library:
      config:
        multiple: false
  - label: Image description
    name: image-description
    widget: string
    required: false
  - label: Image credit
    name: image-credit
    widget: string
    required: false
  - label: "Image size"
    name: "image-size"
    widget: "select"
    options: ["full", "inline", "hidden"]
    required: false
  - label: Byline
    name: byline
    widget: string
    hint: "e.g. Jane Doe / Montana Free Press"
  - label: Body
    name: body
    widget: markdown

collections:
  - label: Graying Pains stories
    label_singular: Graying Pains story
    description: Stories in Graying Pains project
    name: graying-pains
    folder: content/graying-pains
    filter: { field: "type", value: "story" }
    fields: *post-fields
    slug: "gp-{{slug}}"
    format: toml-frontmatter
    extension: md
    create: true
